#azure:
#  cosmosdb:
#    uri: $COSMOSDB_URI
#    key: $COSMOSDB_KEY
#    database: $COSMOSDB_NAME
#    container:
#      feed: $FEED_CONTAINER_ID
#      lease: $LEASE_CONTAINER_ID
management:
  health:
    cosmos:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"